### ISSUE TITLE
Master not compiling

### ISSUE THREAD

**Issue by PlasmaPower** [postiffm/bibledit-gtk#3]
abdf279bcf96dc13946de8f1f4e54667d87b0531 broke compilation, at least on my machine. I'm assuming it's not just me? @postiffm I'm assuming you pushed that to master? You're the author of the commit. We should setup Travis, I'll start working on that.

Relevant error:

```
windowtabbed.h:46:14: error: initializer specified for non-virtual method ‘GtkWidget* Tab::window_get()’
   GtkWidget *window_get() = 0;
              ^~~~~~~~~~
```

**Comment by PlasmaPower** [comment]
I've reverted the commit, fixing compilation here. We can reinstate the commit if it turns out to be a local issue, but better safe than sorry.

**Comment by postiffm** [comment]
Sorry, that was a botch on my part. It is something that I'm not
      done with, but it crept into the commit when I committed the fix
      to the other problem you found.
    
    
    On 7/19/2016 9:53 PM, Lee Bousfield
      wrote:
    
    
      abdf279 broke compilation, at
        least on my machine. I'm assuming it's not just me? @postiffm I'm assuming you pushed
        that to master? You're the author of the commit. We should setup
        Travis, I'll start working on that.
      Relevant error:
      windowtabbed.h:46:14: error: initializer specified for non-virtual method ‘GtkWidget* Tab::window_get()’
   GtkWidget *window_get() = 0;
              ^~~~~~~~~~

      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
